routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::group(['middleware' => 'admin'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('books','BooksController');
});

app/Books.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Books extends Model
{
    protected $fillable = ['category', 'name', 'discription'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Books;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $BooksS = books::latest()->paginate(5);
        return view('books.index',compact('BooksS'))
                ->with('i', (request()->input('page',1)-1)*5 );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'category' => 'required',
        'name' => 'required',
        'discription' => 'required'
      ]);
      books::create($request->all());
      return redirect()->route('books.index')
                       ->with('success', 'new books added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Books = books::find($id);
        return view('books.detail',compact('Books'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Books = books::find($id);
        return view('books.edit' , compact('Books'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'category' => 'required',
            'name' => 'required',
            'discription' => 'required'
        ]);
        $Books = books::find($id);
        $Books->category = $request->get('category');
        $Books->name = $request->get('name');
        $Books->discription = $request->get('discription');
        $Books->save();
        return  redirect()->route('books.index')
                        ->with('success', 'new books updated successfully');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Books = books::find($id);
        $Books -> delete();
        return redirect()->route('books.index')
                        ->with('success', 'Remove Books Successfully' );
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
      //$this->middleware('auth');//first loging
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h3>Add New books</h3>
		</div>
	</div>

	@if ($errors->any())
	<div class="alert alert-danger">
		<strong>Whoops! </strong> There where some problem with your input. <br>
		<ul>
			@foreach ($errors as $error)
			<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
	@endif


	<form action="{{route('books.store')}}" method="post">
      @csrf
		<div class="row">
			<div class="col-md-12">
				<strong>Book category :</strong>
				<input type="text" name="category" class="form-control" placeholder="Enter Book category ">
			</div>
			<div class="col-md-12">
				<strong>Book Name :</strong>
				<input type="text" name="name" class="form-control" placeholder="Enter Book name ">
			</div>
			<div class="col-md-12">
				<strong>Book Discription :</strong>
				<textarea name="discription" class="form-control" placeholder="Enter Book discription " rows="8" cols="80"> </textarea>
			</div>

			<div class="col-md-12">
				<a href="{{route('books.index')}}" class="btn btn-sm btn-success">Back</a>
				<button type="submit" class="btn btn-sm btn-primary ">Submit</button>
			</div>
		</div>
	</form>
</div>

 @endsection

resources/views/books/detail.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Book Details</h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                <strong>Book category:</strong> {{$Books->category}}
                    </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                <strong>Book Name:</strong> {{$Books->name}}
            </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                <strong>Book Discription:</strong> {{$Books->discription}}
            </div>
        </div>
            <div class="col-md-12">
                <a href="{{route('books.index')}}" class="btn btn-sm btn-success">Back</a>
            </div>

        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Edit books</h3>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> There where some problem with your input. <br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif


        <form action="{{route('books.update',$Books->id)}}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-12">
                    <strong>Book category :</strong>
                    <input type="text" name="category" class="form-control" value="{{$Books->category}}">
                </div>
                <div class="col-md-12">
                    <strong>Book Name :</strong>
                    <input type="text" name="name" class="form-control" value="{{$Books->name}}">
                </div>
                <div class="col-md-12">
                    <strong>Book Discription :</strong>
                    <textarea class="form-control" name="discription"  rows="8" cols="80">{{$Books->discription}}</textarea>
                </div>

                <div class="col-md-12">
                    <a href="{{route('books.index')}}" class="btn btn-sm btn-success">Back</a>
                    <button type="submit" class="btn btn-sm btn-primary ">Submit</button>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/books/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h3>
				Book List
			</h3>
		</div>
		<div compact="col-sm-2">
			<a class="btn btn-sm btn-success" href="{{ route('books.create') }}">Add New Book</a>
		</div>
	</div>
   @if($message = Session::get('success') )
   <div class="alert alert-success">
    <p> {{$message}} </p>
   </div>
   @endif
   <table class="table table-hover table-sm">
	<tr>
		<th width="50px"><b>NO. </b> </th>
		<th width="300px">Category</th>
		<th>Name</th>
        <th>Discription</th>
		<th width="180px">Action</th>
	</tr>
	@foreach ($BooksS as $Books)
	<tr>
		<td><b> {{++$i}}. </b></td>
		<td> {{$Books->category}} </td>
		<td> {{$Books->name}} </td>
		<td> {{$Books->discription}} </td>
		<td>
			<form action="{{ route('books.destroy', [$Books->id])  }}" method="post">
				<a class="btn btn-sm btn-success" href="{{ route('books.show' , [$Books->id]) }}">Show</a>
				<a class="btn btn-sm btn-warning" href="{{ route('books.edit' , [$Books->id]) }}">Edit</a>
				@csrf
				@method('DELETE')
				<button type="submit" class="btn btn-sm btn-danger">Delete</button>

			</form>
		</td>
	</tr>
	@endforeach

</table>

{!! $BooksS->links()  !!}


</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                        @if(auth()->user()->is_admin == 1)
                            <div class=”panel-heading”>Admin</div>
                        @else
                            <div class=”panel-heading”>Normal User</div>
                        @endif
                    <br>
                        <br>

                    You are logged in, {{ Auth::user()->name }}  <br>


                        <a href="{!! route('books.index') !!}">View all books</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>